server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "D:\\GoProject\\ms_project\\logs\\debug\\debug.log"
  infoFileName: "D:\\GoProject\\ms_project\\logs\\info\\info.log"
  warnFileName: "D:\\GoProject\\ms_project\\logs\\error\\error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"