server:
  name: "project-task"
  addr: "127.0.0.1:8081"
zap:
  debugFileName: "D:\\GoProject\\ms_project\\logs\\debug\\debug.log"
  infoFileName: "D:\\GoProject\\ms_project\\logs\\info\\info.log"
  warnFileName: "D:\\GoProject\\ms_project\\logs\\error\\error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "task"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "msproject"